apiVersion: apps/v1
kind: Deployment
metadata:
  name: apitree-demo-deployment
spec:
  selector:
    matchLabels:
      app: apitree-demo
  replicas: 2
  template:
    metadata:
      labels:
        app: apitree-demo
    spec:
      containers:
      - name: hello
        image: "nginxdemos/hello"
        env:
        - name: "PORT"
          value: "80"